workspace:
  base: /go

pipeline:
  build:
    image: golang:1.6
    commands:
      - CGO_ENABLED=0 go build

  docker:
    storage_driver: overlay
    repo: plugins/s3
    tag: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: S3
  desc: Publish files and artifacts to Amazon S3
  type: publish
  image: plugins/s3
  labels:
    - publish
    - artifacts
    - amazon
    - aws
    - s3
