clone:
  git:
    image: plugins/git:next

pipeline:
  test:
    image: golang:1.16
    commands:
      - go test -race -cover ./...

  vet:
    image: golang:1.16
    commands:
      - go vet ./...

  build:
    image: golang:1.16
    commands:
      - go build
